FROM ubuntu:focal

#Install Java
RUN apt-get update
RUN apt-get install -y openjdk-11-jdk
RUN java -version

#Install prereqs
RUN apt-get install -y apt-transport-https
RUN apt-get install -y ca-certificates
RUN apt-get install -y curl
RUN apt-get install -y gnupg
RUN apt-get install -y openssh-server
RUN apt-get install -y git
RUN apt-get install -y iptables

#Install and setup Jenkins:
RUN curl -fsSL https://pkg.jenkins.io/debian-stable/jenkins.io.key | tee /usr/share/keyrings/jenkins-keyring.asc > /dev/null
RUN echo deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/ | tee /etc/apt/sources.list.d/jenkins.list > /dev/null
RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys FCEF32E745F2C3D5
RUN apt-get update
RUN apt-get install -y jenkins
RUN mkdir /example-web
RUN mkdir -p /var/lib/jenkins/.ssh/
RUN chown -R jenkins:jenkins /var/lib/jenkins
RUN mkdir -p /jenkins
RUN chown -R jenkins:jenkins /jenkins
RUN runuser -l jenkins -c 'ssh-keygen -q -b 2048 -t rsa -f /var/lib/jenkins/.ssh/id_rsa -N ""'
RUN runuser -l jenkins -c 'git ls-remote -h https://github.com/metalyc/web-example.git HEAD'

#Install docker
#RUN curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
#RUN echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu (lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
RUN wget -q https://download.docker.com/linux/ubuntu/dists/focal/pool/stable/amd64/containerd.io_1.4.9-1_amd64.deb
RUN wget -q https://download.docker.com/linux/ubuntu/dists/focal/pool/stable/amd64/docker-ce_20.10.9~3-0~ubuntu-focal_amd64.deb
RUN wget -q https://download.docker.com/linux/ubuntu/dists/focal/pool/stable/amd64/docker-ce-cli_20.10.9~3-0~ubuntu-focal_amd64.deb
RUN dpkg -i *.deb

#Install and setup Kubectl:
RUN curl -fsSLo /usr/share/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg
RUN echo "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | tee /etc/apt/sources.list.d/kubernetes.list
RUN apt-get update
RUN apt-get install -y kubectl

EXPOSE 8080

CMD service jenkins start && tail -F /var/lib/jenkins/secrets/initialAdminPassword
